name: build

on:
  release:
    types:
      - created
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
  MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main
      - name: Set up Java 21
        uses: actions/setup-java@main
        with:
          distribution: 'temurin'
          java-version: '21'
          server-id: henkelmax.public
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Setup zig
        uses: mlugg/setup-zig@main
        with:
          version: 0.14.1
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@main
        with:
           allow-snapshot-wrappers: true
      - name: Build and deploy
        run: |
          ./gradlew build
          mkdir -p release
          cp $(find ./build/libs -maxdepth 1 -type f -name "*.jar") ./release/
      - uses: actions/upload-artifact@main
        with:
          name: opus4j-java
          path: ./release/

      - uses: actions/upload-artifact@main
        if: failure()
        with:
          name: libopus4j
          path: |
                **/libopus4j.so
